version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
        - "3307:3306"
    volumes:
        - recipe_jar_mysql:/var/lib/mysql

  app:
    build: .
    command: "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    environment:
        - SECRET_KEY=${SECRET_KEY}
        - DB_NAME=${DB_NAME}
        - SECRET_KEY=${SECRET_KEY}
        - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
        - DEBUG=${DEBUG}
    volumes:
      - .:/app
    ports:
        - "8000:8000"
    depends_on:
        - db

volumes:
    recipe_jar_mysql:

