# Generated by Django 4.2.8 on 2024-05-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='video_posted_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
