name: Build and Deploy

on:
  push:
    branches: 'main'

jobs:
    deploy:
      runs-on: ubuntu-latest
      
      steps:
        - name: Deploy Django Project
          uses: appleboy/ssh-action@v0.1.2
          with:
            host: ${{secrets.SSH_HOST}}
            key: ${{secrets.SSH_KEY}}
            username: ${{secrets.SSH_USERNAME}}
            passphrase: ${{secrets.PASSPHRASE}}
    
            script: |
              mkdir recipe-jar
              cd recipe-jar
              git clone git@github.com:Abdulhafeez012/Recipe-Jar.git
              echo 'Deployment Via Digital Ocean Successfully"
    
        
